services:
  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    image: cpf_simulator_frontend
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_BACKEND_API_URL: https://backendapi.ccutrainingsimulator.com
    volumes:
      - ./admin-dashboard:/admin-dashboard
      - /admin-dashboard/.next
    restart: unless-stopped

  final-csa-dashboard:
    build:
      context: ./final-csa-dashboard
      dockerfile: Dockerfile
    image: cpf_simulator_trainee_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_API_URL: https://backendapi.ccutrainingsimulator.com
    volumes:
      - ./final-csa-dashboard:/final-csa-dashboard
      - /final-csa-dashboard/.next
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cpf_simulator_backend_connected_to_aws_rdb
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
