services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cpf_simulator_backend_connected_to_aws_rdb
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
