version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cpf_simulator_backend_connected_to_aws_rdb
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/backend
